# Generated by Django 3.0.6 on 2020-06-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200603_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
