# Generated by Django 3.0.6 on 2020-06-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_cliente_telefone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Telefone',
        ),
    ]
