# Generated by Django 3.0.6 on 2020-06-03 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Telefone'),
            preserve_default=False,
        ),
    ]
