# Generated by Django 3.0.6 on 2020-06-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200603_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='telefone',
            new_name='numeroCelular',
        ),
    ]
